### ISSUE TITLE
TTL Deletion Hook

### ISSUE THREAD

**Issue by four43** [tkem/cachetools#103]
I need to hook into when a cache item is removed from a TTLCache. It seems that `expire()` doesn't call it's local `__delitem__()` or the `popitem()` methods when an item is removed via expiration. Are you interested in a pull request for this feature?

**Comment by tkem** [comment]
`popitem()` is only called when items are removed when a cache is full to make room for new items. Items whose TTL expires just vanish into thin air, because you told them to do so after a certain time ;-)
Unless this is a popular use case I just haven't heard about so far, I'd prefer to *not* add any special handling for this.

**Comment by four43** [comment]
I was using this to managed locally cached files. I needed a hook to for when an item is deleted from the cache so I can remove them from my temporary directory. This library was too inflexible and I ended up just writing my own.

**Comment by momocow** [comment]
I met the same requirements, cached files, and came up with this library in mind. But it seems that I should implement my own cache to play with cached files.
