### ISSUE TITLE
Ttl cache does not protect itself from KeyError when entry doesn't exist during expire()

### ISSUE THREAD

**Issue by brunoais** [tkem/cachetools#115]
Problem:

In multithreaded environments, there's a high chance that [`def expire(self, time=None)`](https://github.com/tkem/cachetools/blob/master/cachetools/ttl.py#L170) is called concurrently.
When that happens, there's a chance that `cache_delitem` (`Cache.__delitem__`) is called multiple times for the same element.
When that function is called multiple times, the operator ends up executing `del` over the cache Mapping which causes an undocumented `KeyError` on all but first call to clear the cache entry.

To reproduce:
1. Create a function with many calls. For example:

```
from threading import Thread
import cachetools
import random
@cachetools.cached(cachetools.TTLCache(maxsize=50, ttl=1))
def will_not_be_called_sometimes(value):
	import time
	time.sleep(value / 5)
random.seed(5)
def run():
	while True:
		will_not_be_called_sometimes(random.randrange(1, 30))
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
Thread(target=run).start()
run()
```

2. Run as much as needed until the exception starts to appear.

Note: In order to work, it might require running the program in a system with multiple CPU or CPU cores.

**Comment by tkem** [comment]
https://cachetools.readthedocs.io/en/latest/#cache-implementations

> Please be aware that Cache and its subclasses are not thread-safe. Access to a shared cache from multiple threads must be properly synchronized, e.g. by using one of the memoizing decorators with a suitable lock object.

**Comment by brunoais** [comment]
Ups. I failed to check that `TtlCache` extends `Cache`. Thanks.

**Comment by tkem** [comment]
Hmmm... maybe it should say "all cache classes in this module" or something like that instead "Cache and its subclasses". Would that be clearer? Suggestions welcome!

**Comment by brunoais** [comment]
> "all cache classes in this module"
Yeah, that is a good improvement (I'm also awful with these stuff). Thank you.

**Comment by tkem** [comment]
OK, I'll think about it. Thanks for your feedback - I thought the note in the docs was pretty clear, but obviously it's not :-)

**Comment by tkem** [comment]
@theahura As already stated [elsewhere](https://github.com/tkem/cachetools/issues/245#issuecomment-1179785529) , at the time you get the `KeyError` your cache's internal data structures may already have become corrupted, leading to all kind of interesting effects.
So start seeing the `KeyError` as a feature that reminds you that something is wrong with your code.

**Comment by theahura** [comment]
Thanks for the reply!

Can you help me understand how the internal data structures would be corrupted in a multi threaded multi access environment? 

Let me explain my mental model, and maybe you can help point out why I'm way off base 😂

As far as I can tell, there are two functions that matter for my use case -- set, and get. 

When setting, I don't particularly care if my data gets overwritten because something is already in the cache. I'm having trouble imagining other possible race conditions that might corrupt set behavior.

When getting, I don't particularly care if data is present that was supposed to be deleted, ie it's fine if the cache is eventually consistent across threads instead of strongly consistent. Again, besides this, I'm having trouble thinking through other possible race conditions. 

Implementing a lock isn't that hard, so it's not that big an issue. I'm just curious from a technical perspective, to better understand the limits of this dependency
