### ISSUE TITLE
TTLCache class\decorator LFU (and possibly other algorithms) support

### ISSUE THREAD

**Issue by naorlivne** [tkem/cachetools#120]
It's my understanding that TTLCache provides a max TTL for each value as well as protection against the max cache length and where cases that the cache length is about to overflow the max length a LRU function is used to choose the LRU value to remove from the cache... There are cases you might want to have a TTL Cache alongside LFU or other algorithms as the deciding algorithm for when the cache length is maxed.

My suggestion to add it is to allow setting the algorithm choice when declaring the TTLCache decorator\ initializing the class with LRU being the default value of said parameter.

**Comment by naorlivne** [comment]
Also think this might be related to #114 as it's another cache strategy.

**Comment by tkem** [comment]
I thought about this myself initially, e.g. implementing the `ttl` stuff as a class decorator or something, but implementing it this way turned out to be more difficult than expected and probably more hassle than it's worth - LRU seems to be a sensible choice for many use cases. 
So feel free to try your hand at this, but it's nothing I plan to pick up again.

**Comment by naorlivne** [comment]
Probably won't have time for that either & agreed that LRU is a sensible choice for a lot of cases, just not all of them.

**Comment by tkem** [comment]
Fair enough.
