### ISSUE TITLE
maxsize=None doesn't work with python3

### ISSUE THREAD

**Issue by ndamclean** [tkem/cachetools#141]
comparisons with `None` and `int` values raise errors in python 3

**Comment by tkem** [comment]
Nice catch! Though I could swear, I already had a unit test for that...
Will look into your PR ASAP!

**Comment by tkem** [comment]
After looking into your PR, I realized I misinterpreted this.
Actually, `maxsize=None` is only supported for the `cachetools.func` decorators: https://cachetools.readthedocs.io/en/latest/#module-cachetools.func
What makes you think passing `maxsize=None` to a `Cache` constructor should be valid? Because it's not. So that this raises an error in Python 3 is the desired behavior. Maybe this should have been checked explicitly for Python 2, but it's a little late for that now.

**Comment by ndamclean** [comment]
IMO the ability to set `maxsize` to `None` to unlimited would be a useful feature for some caching strategies (e.g. `TTLCache`)

**Comment by tkem** [comment]
@ndamclean: Regarding your first comment: They don't mention that `maxsize` can be set to `None`, either ;-) They also state in the introduction, that

> For the purpose of this module, a cache is a mutable mapping of a fixed maximum size. 

But I agree, the docs could state this more clearly. Given that this seems to work with Python 2.7, which I didn't realize, it may surprise people porting their code to Python 3. So I'll consider that, thanks!

Regarding your second comment, I do disagree somewhat. For three out of four cache implementations (LRU, LFU, RR) this doesn't make sense really, and you'd be better off using a plain `dict` (which you can also use with the caching decorators). For TTL, you'd really want an "expiring dict", which doesn't have the additional overhead of checking `maxsize`, etc. Maybe someone has already implemented something like that, otherwise feel free to adapt the code from `TTLCache` accordingly.

That being said, it actually _is_ already possible to achieve the desired behavior without explicitly supporting it or me encouraging this: `TTLCache(maxisze=float('inf'))` should do the trick.

**Comment by ndamclean** [comment]
@tkem Actually, I just tested this in python 2.7.

```python
from cachetools import TTLCache
tc = TTLCache(maxsize=None, ttl=10)
tc[0] = 0
```

This raises `ValueError: value too large`, so it seems as if in python 2, `maxsize=None` is the same as `maxsize=0`, which seems like sensible behaviour.

I guess you don't think you need to worry about changing anything.

Thanks for the `TTLCache(maxisze=float('inf'))` suggestion.

**Comment by tkem** [comment]
Well, kudos to @sublee, who brought this up in #73.

**Comment by sublee** [comment]
@tkem Thank you for your respect :)

**Comment by gandhis1** [comment]
Why exactly does `maxsize=None` not make sense for something like `TTLCache`? This is the convention in `functools`, it's pretty well understood. I'm fine using `float("inf")` but this is counter to what I think most would expect.
