### ISSUE TITLE
TTLcache don't clear memory

### ISSUE THREAD

**Issue by Vasiliy566** [tkem/cachetools#177]
so i run this script to check memory usage of TTLcache:
```
from cachetools import TTLCache
import time
import psutil
cache = TTLCache(maxsize=5000, ttl=10)

print(psutil.virtual_memory())
print("started")
for i in range(5000):
    cache[i] = "AAAAAA" * 1000000
print(psutil.virtual_memory())
print("finished")
time.sleep(50)
print(psutil.virtual_memory())
```
And get thar output:
```
svmem(total=67457380352, available=56445067264, percent=16.3, used=9796333568, free=30661332992, active=15309488128, inactive=19676790784, buffers=284905472, cached=26714808320, shared=467402752)
started
svmem(total=67457380352, available=26374475776, percent=60.9, used=39866925056, free=590708736, active=45323694080, inactive=19676786688, buffers=284905472, cached=26714841088, shared=467402752)
finished
svmem(total=67457380352, available=26366201856, percent=60.9, used=39875198976, free=582213632, active=45330063360, inactive=19676934144, buffers=284913664, cached=26715054080, shared=467406848)
```
Does it means that TTLcache realy not clear memory after time said as TTL=N ends?
P.S. it realy works that i have no acess to elements after TTL, but memory still busy

**Comment by tkem** [comment]
As stated [in the docs](https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache.expire),

> Expired items will be removed from a cache only at the next mutating operation, e.g. __setitem__() or __delitem__(), and therefore may still claim memory.

So no memory will actually be freed just sleeping. You need to add or delete cache items to see any effect. Additionally, since Python uses garbage collection, the time between an application "freeing" memory and the Python interpreter actually returning that memory to the OS is indeterminate.

**Comment by Vasiliy566** [comment]
@tkem thx, usefull for me
