### ISSUE TITLE
The usual way to set permanent keys in cache?

### ISSUE THREAD

**Issue by thec0sm0s** [tkem/cachetools#186]
Hello thanks for this super handy project.

So I need to set few keys in cache which should exist permanently regardless of cache maxsize (like as it would in normal dict). What would be the usual way to acheive this implementation?

What I thought of initially was to somehow override and make `.getsizeof()` return 0 for permanent keys? Or there is any better way for same implementation?

**Comment by tkem** [comment]
Never came across this requirement before, but `getsizeof()` probably won't do the trick, since a size of 0 will not prevent the cache item from being discarded.
Maybe overriding `__missing__` to return your "permanent" items would be an option? This way, your "default" items could also be temporarily overridden.

**Comment by thec0sm0s** [comment]
yeahh true, I actually tried using getsizeof() to mark my permanent elements "absent" in cache and then somehow override the default popitem() to ignore the permanent keys. But this way sounds inefficient.

Now I feel yeah, overriding `__missing__` can really help me here. So what I can do is have another protected dict instance to store only the permanent elements in cache and server them using __missing__. What you think of this implementation.

Thanks for your help!

**Comment by tkem** [comment]
Yes, I think as soon as #200 is fixed, this would be a valid option ;-)
