### ISSUE TITLE
Evict callback for TTLCache

### ISSUE THREAD

**Issue by arossert** [tkem/cachetools#205]
I'm missing the option to set a callback when an item is evicted using the `TTLCache`.
I tried using the solution detailed [here](https://github.com/tkem/cachetools/pull/48) but it seems that the `TTLCache` is working a bit differently then the others and not calling the `popitem()` when entries are evicted by timeout.

Is there a way to get a callback when an item is deleted also by timeout? 
I tried overriding the `expire()` function with no success.

**Comment by hellocoldworld** [comment]
If I understand the docs correctly, items are only evicted by timeout when you try to access them but the item has expired. So, the method you would need to override is `__get_item__`

**Comment by tkem** [comment]
@arossert Sorry, there is no way to get notified when a `TTLCache` item expires.

**Comment by arossert** [comment]
@tkem Thanks for the update, it will be a coll feature to add 😃

**Comment by tkem** [comment]
To take this into consideration, somebody would have to come up with a _really_ good use case...

**Comment by charliejacobsen** [comment]
Yes, it would be nice to have this @tkem. (It would also be nice if cachetools didn't use double underscores on member fields as this makes it less friendly to subclassing.)

I'm using TTLCache as trick to doing a TTL-based connection pool, and I'd like to close a connection as soon as it's evicted, rather than waiting till it is garbage collected.

**Comment by charliejacobsen** [comment]
eh, on second thought, there's too many edge cases to worry about (delitem, setitem, expire, and more). I'll stick with "wait for gc" and see if that suffices for me.

**Comment by jarekrutowicz** [comment]
> To take this into consideration, somebody would have to come up with a _really_ good use case...

I think there are many examples you can think of. For example waiting for a async request response with req_id key. If the response does not come within a timeout then evict the cache. I would like to know what requests I didn't know have a reply and were droped. It would be very usefull to be able at least to log that.

**Comment by arossert** [comment]
In my case, I'm using the `TTLCache` as a pool of connection tokens that will be evicted after some time, I would like to know if the pool is empty to alert that a new token needs to be generated (without polling on the pool).

**Comment by dberardo-com** [comment]
if TTLCache is not timer-based, then there is no event that one could "subscribe to" inside the code. Based on this comment: https://github.com/tkem/cachetools/issues/205#issuecomment-800470199 i believe that this is not the case, and so i think it will be misleading to offer a "on('expired')" callback for TTLCache, as the frequency will not be deterministic.

Please correct me if i am wrong, because i also have a use case for using such function in TTLCache. And basically i dont want to handle a pool of Timers myself.

all in all, you could look at this library as an alternative depending on your use case: https://github.com/dbader/schedule

**Comment by jarekrutowicz** [comment]
> i believe that this is not the case, and so i think it will be misleading to offer a "on('expired')" callback for TTLCache, as the frequency will not be deterministic.

How is that misleading? No matter what is the eviction policy I would like to know when the case was evicted. If the frequency is not deterministic then having a callback is actually more useful.

**Comment by dberardo-com** [comment]
i see your point, perhaps using good naming conventions could prevent misunderstandings, or perhaps a big disclaimer on the documentation of such an event hook could do the job :)

cheers

**Comment by arossert** [comment]
I can see this to be very useful
