### ISSUE TITLE
Expose wrapping dict

### ISSUE THREAD

**Issue by maartenbreddels** [tkem/cachetools#232]
The cache classes as they are now are basically a 'proxy' around a real dict (self.__data). I wonder if it makes sense to take an optional mutable mapping argument, and use that instead of a dict, this makes this library much more flexible. Does this make sense? (e.g. by having a MutableMapping implementation that writes to disk)

**Comment by mivade** [comment]
I just wanted to chime in here that I too would like to be able to pass in an arbitrary dict-like object to use as the actual backend. I have only recently started using this library and have use cases where I'd like to be able to cache data using the filesystem as a backend in one way or another. Using the `cached` decorator I can already do this by just passing in e.g. a `shelve.Shelf` instance. This is great and covers a great deal of what I need. But sometimes I'd also like to be able to use some of the caching algorithms that `cachetools` provides (LRU caching, TTL caching, etc.). The provided classes all use a private `__data` attribute that lives in memory which means that I'd have to completely reimplement the algorithms if I want to use something other than a regular `dict`. It would be great if `Cache.__init__` had an optional argument to allow me to select an arbitrary `MutableMapping` to use instead of `dict`.

I'd be happy to submit a PR if you're open to this @tkem.
